In [1]:
# library
import numpy as np

## Array operations

In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr2

array([ 6,  7,  8,  9, 10])

In [10]:
# arithmetic operations
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [11]:
# subtraction of arrays
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [12]:
# multiplication of arrays
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [14]:
# division of arrays
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [15]:
# floor of arrays
arr1 // arr2

array([0, 0, 0, 0, 0])

In [16]:
# exponents of arrays
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

## Array Broadcasting

In [17]:
list = [10, 20, 30 ,40]
arr = np.array(list)

In [19]:
# add 10 to all values in list
list + 10

TypeError: can only concatenate list (not "int") to list

In [20]:
# add 10 to all values in arrays
arr + 10

array([20, 30, 40, 50])

In [21]:
# broadcasting in matrix
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [24]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

## Matrix Operations

In [29]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [8,9]])
arr1

array([[1, 2],
       [3, 4]])

In [30]:
arr2

array([[5, 6],
       [8, 9]])

In [32]:
# Dot product multiplication
arr1 @ arr2

array([[21, 24],
       [47, 54]])

In [34]:
# numpy
arr3 = np.dot(arr1, arr2)
arr3

array([[21, 24],
       [47, 54]])

In [36]:
# transpose
arr3.T

array([[21, 47],
       [24, 54]])

## Advance Array Manipulation

In [39]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [40]:
arr1

array([1, 2, 3, 4])

In [41]:
arr2

array([5, 6, 7, 8])

In [44]:
# vertical stack
vStack = np.vstack((arr1, arr2))
vStack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# horizontal stack
hStack = np.hstack((arr1, arr2))
hStack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
# columns stack
columnStack = np.column_stack((arr1, arr2))
columnStack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [49]:
# splitnp.column
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]