In [1]:
import numpy as np

## Exercise

In [6]:
# marks of students
# columns: [Age, MathsMarks, ScienceMarks]
data = np.array([
    [18, 85, 78], # student 1
    [19, 92, 88], # student 2
    [17, 76, 95], # student 3
    [18, 65, 70], # student 4
    [20, 90, 85]  # student 5
])

In [3]:
# shape of matrix
data.shape

(5, 3)

In [16]:
# average age of students
age = data[:, 0]
avgAge = age.mean()
avgAge

np.float64(18.4)

In [17]:
# extract math marks of all students
mathsMarks = data[:, 1]
mathsMarks

array([85, 92, 76, 65, 90])

In [20]:
# extract highest Science marks
scienceMarks = data[:, 2]
highestMarks = scienceMarks.max()
highestMarks

np.int64(95)

In [30]:
# extract students having MATH marks > 90
highestMathMarks = data[:, 1]
marks = highestMathMarks >= 90
result = highestMathMarks[marks]
result

array([92, 90])

In [34]:
# increase math marks of all students by 5
newData = data.copy()
newMathMarks = newData[:, 1]
newMathMarks + 5

array([90, 97, 81, 70, 95])

In [36]:
# extract students younger than 19
youngAge = data[:, 0]
result = youngAge[youngAge < 19]
result

array([18, 17, 18])

In [42]:
# extract the average of MATHS and SCIENCE
avgMathsMarks = data[:, 1]
avgScienceMarks = data[:, 2]
meanMathMarks = avgMathsMarks.mean()
meanScienceMarks = avgScienceMarks.mean()
meanScienceMarks

np.float64(83.2)

In [47]:
# extract students score atleast 80 in both subjects
student = data[0:, 1:]
condition = (student[:, 0] >= 80) & (student[:, 1] >= 80)
result = student[condition]
result

array([[92, 88],
       [90, 85]])

In [64]:
# replace all SCIENCE marks < 70 with 0
sliceData = newData[:, 2]
condition = (sliceData <= 70)
result = sliceData[condition] = 0
result

0